// src/lib/vue/input.vue
<script lang="ts" setup>
import '../../css/input.css'

withDefaults(
	defineProps<{
		placeholder: string
		autofocus: boolean
		autocomplete: boolean
		spellcheck: boolean
		value: string
	}>(),
	{
		autofocus: false,
		autocomplete: false,
		spellcheck: false
	}
)

defineEmits(['update:value'])
</script>

<template>
	<div class="input__container">
		<input
			class="input__input"
			:value="value"
			@input="$emit('update:value', ($event.target as HTMLInputElement).value)"
			:autofocus="autofocus"
			:autocomplete="autocomplete ? 'on' : 'off'"
			:spellcheck="spellcheck ? 'true' : 'false'"
			:id="placeholder"
			:placeholder="placeholder"
		/>
		<label
			:for="placeholder"
			class="input__label"
		>
			<slot />
		</label>
	</div>
</template>

// src/lib/input.svelte
<script lang="ts">
	import '../css/input.css'
	export let placeholder = ''
	export let autofocus = false
	export let autocomplete = false
	export let spellcheck = false
	export let value = ''

	function handleInput(e: Event) {
		value = (e.target as HTMLInputElement).value
	}
</script>

<div class="input__container">
	<!-- svelte-ignore a11y-autofocus -->
	<input
		{value}
		{autofocus}
		on:input={handleInput}
		class="input__input"
		autocomplete={autocomplete ? 'on' : 'off'}
		spellcheck={spellcheck ? 'true' : 'false'}
		id={placeholder}
		{placeholder}
	/>
	<label for={placeholder} class="input__label">
		{placeholder}
	</label>
</div>
