// src/lib/react/input.tsx
import React, { useCallback } from 'react'
import '../../css/input.css'

interface InputProps {
	children: React.ReactNode

	placeholder?: string
	autofocus?: boolean
	autocomplete?: boolean
	spellcheck?: boolean

	value: string
	setValue: (value: string) => void
}

const Input = (props: InputProps) => {
	const inputId = React.useId()

	const handleInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
		props.setValue(e.target.value)
	}, [])

	return (
		<div className="input__container">
			<input
				id={inputId}
				value={props.value}
				onChange={handleInput}
				className="input__input"
				placeholder={props.placeholder}
				autoFocus={props.autofocus}
				autoComplete={String(props.autocomplete)}
				spellCheck={props.spellcheck}
			/>
			<label
				htmlFor={inputId}
				className="input__label"
			>
				{props.children}
			</label>
		</div>
	)
}

export default Input

// src/lib/input.svelte
<script lang="ts">
	import '../css/input.css'
	export let placeholder = ''
	export let autofocus = false
	export let autocomplete = false
	export let spellcheck = false
	export let value = ''

	function handleInput(e: Event) {
		value = (e.target as HTMLInputElement).value
	}
</script>

<div class="input__container">
	<!-- svelte-ignore a11y-autofocus -->
	<input
		{value}
		{autofocus}
		on:input={handleInput}
		class="input__input"
		autocomplete={autocomplete ? 'on' : 'off'}
		spellcheck={spellcheck ? 'true' : 'false'}
		id={placeholder}
		{placeholder}
	/>
	<label for={placeholder} class="input__label">
		{placeholder}
	</label>
</div>
