// src/lib/svelte/modal.svelte
<script lang="ts">
	import RainbowBlock from './rainbow-block.svelte'
	import '../../css/modal.css'

	export let isOpen: boolean
	export let close = () => {}
	export let base_width = 300
</script>

<svelte:body on:keydown={(e) => e.key === 'Escape' && isOpen && close()} />

{#if isOpen}
	<!-- svelte-ignore a11y-no-static-element-interactions a11y-click-events-have-key-events -->
	<section on:mousedown={close} class="modal__wrapper">
		<div style={`width: ${Math.max(base_width, 200)}px;`}>
			<RainbowBlock>
				<slot />
				<div>
					<span on:click={close} class="modal__close-button">X</span>
				</div>
			</RainbowBlock>
		</div>
	</section>
{/if}

// src/lib/vue/modal.vue
<script setup lang="ts">
import RainbowBlock from './rainbow-block.vue'
import '../../css/modal.css'
import { computed } from 'vue'

const props = withDefaults(
	defineProps<{
		isOpen: boolean
		close: () => void
		base_width: number
	}>(),
	{
		base_width: 300
	}
)

const w = computed(() => {
	return Math.max(props.base_width, 200) + 'ms'
})
</script>

<template>
	<section
		@mousedown="close"
		class="modal__wrapper"
	>
		<div class="size">
			<RainbowBlock>
				<slot />
				<div>
					<span
						@click="close"
						class="modal__close-button"
						>X</span
					>
				</div>
			</RainbowBlock>
		</div>
	</section>
</template>

<style>
.size {
	width: v-bind(w);
}
</style>
