// package-svelte/src/svelte/input.svelte
<script>import "../../css/input.css";
export let placeholder = "";
export let autofocus = false;
export let autocomplete = false;
export let spellcheck = false;
export let value = "";
function handleInput(e) {
  value = e.target.value;
}
</script>

<div class="input__container">
	<!-- svelte-ignore a11y-autofocus -->
	<input
		{value}
		{autofocus}
		on:input={handleInput}
		class="input__input"
		autocomplete={autocomplete ? 'on' : 'off'}
		spellcheck={spellcheck ? 'true' : 'false'}
		id={placeholder}
		{placeholder}
	/>
	<label for={placeholder} class="input__label">
		<slot />
	</label>
</div>

// package-react/src/react/input.js
import React, { useCallback } from 'react';
import '../../css/input.css';
var Input = function (props) {
    var inputId = React.useId();
    var handleInput = useCallback(function (e) {
        props.setValue(e.target.value);
    }, []);
    return (React.createElement("div", { className: "input__container" },
        React.createElement("input", { id: inputId, value: props.value, onChange: handleInput, className: "input__input", placeholder: props.placeholder, autoFocus: props.autofocus, autoComplete: String(props.autocomplete), spellCheck: props.spellcheck }),
        React.createElement("label", { htmlFor: inputId, className: "input__label" }, props.children)));
};
export default Input;
